### Merge

Porównanie metod merge i concat

In [10]:
import pandas as pd

df1 = pd.DataFrame({ 'key': ['A', 'B'], 'x': [1, 2]})

df2 = pd.DataFrame({ 'key': ['B', 'C'], 'y': [10, 20]})

display(df1)
display(df2)

  key  x
0   A  1
1   B  2

  key   y
0   B  10
1   C  20

>> Concat

In [11]:
concat_outer = pd.concat([df1, df2], join='outer', ignore_index=True)
concat_inner = pd.concat([df1, df2], join='inner', ignore_index=True)

display("Outer concat: ", concat_outer)
display("Inner concat: ", concat_inner)

'Outer concat: '

  key    x     y
0   A  1.0   NaN
1   B  2.0   NaN
2   B  NaN  10.0
3   C  NaN  20.0

'Inner concat: '

  key
0   A
1   B
2   B
3   C

>> Merge

In [12]:
outer_merge = df1.merge(
    df2, 
    on='key',
    how='outer'
)
inner_merge = df1.merge(
    df2, 
    on='key',
    how='inner'
)

left_merge = df1.merge(
    df2, 
    on='key',
    how='left'
)

right_merge = df1.merge(
    df2, 
    on='key',
    how='right'
)

In [13]:
from IPython.display import Markdown
display(df1)
display(df2)

display(Markdown("### Outer concat: "), concat_outer)
display(Markdown("### Inner concat: "), concat_inner)
display(Markdown("### Outer merge: "), outer_merge)
display(Markdown("### Inner merge: "), inner_merge)
display(Markdown("### Left merge: "), left_merge)
display(Markdown("### Right merge: "), right_merge)

  key  x
0   A  1
1   B  2

  key   y
0   B  10
1   C  20

### Outer concat:

  key    x     y
0   A  1.0   NaN
1   B  2.0   NaN
2   B  NaN  10.0
3   C  NaN  20.0

### Inner concat:

  key
0   A
1   B
2   B
3   C

### Outer merge:

  key    x     y
0   A  1.0   NaN
1   B  2.0  10.0
2   C  NaN  20.0

### Inner merge:

  key  x   y
0   B  2  10

### Left merge:

  key  x     y
0   A  1   NaN
1   B  2  10.0

### Right merge:

  key    x   y
0   B  2.0  10
1   C  NaN  20


---
### JOIN

>> syntax podobny do merge, z od góry zdefiniowanym "on" index `result = df1.join(df2, how=?)`

#### Zadanie 1 - join na indeksie z różnymi strategiami

Masz tabelę produktów i tabelę z danymi magazynowymi. 

Połącz je metodą join() (na indeksie). 

Produkt_id jest indeksem obu tabel. 

Porównaj wyniki dla how='left', 'right', 'inner', 'outer' i wyjaśnij różnice.

In [14]:
import pandas as pd
import numpy as np

produkty = pd.DataFrame({
    'nazwa': ['Laptop', 'Mysz', 'Monitor', 'Klawiatura', 'Słuchawki'],
    'cena': [3500, 120, 900, 250, 400],
    'kategoria': ['PC', 'Akcesoria', 'PC', 'Akcesoria', 'Audio']
}, index=[101, 102, 103, 104, 105])

produkty.index.name = 'produkt_id'  # nazwany index

magazyn = pd.DataFrame({
    'stan': [15, 0, 8, 32, 5],
    'lokalizacja': ['A1', 'B3', 'A2', 'C1', 'B1'],
    'ostatnia_dostawa': ['2024-03-01', '2024-01-15', '2024-03-10', '2024-02-20', '2024-03-05']
}, index=[101, 102, 103, 106, 107])

magazyn.index.name = 'produkt_id'

In [15]:
display(produkty, magazyn)

                 nazwa  cena  kategoria
produkt_id
101             Laptop  3500         PC
102               Mysz   120  Akcesoria
103            Monitor   900         PC
104         Klawiatura   250  Akcesoria
105          Słuchawki   400      Audio

            stan lokalizacja ostatnia_dostawa
produkt_id
101           15          A1       2024-03-01
102            0          B3       2024-01-15
103            8          A2       2024-03-10
106           32          C1       2024-02-20
107            5          B1       2024-03-05

In [26]:
display(Markdown('>> ### LEFT JOIN (wszystkie wiersze z lewej ramki + pasujące z prawej)'))
left_join = produkty.join(magazyn, how='left')
display(left_join)

display(Markdown('>> ### RIGHT JOIN (wszystkie wiersze z prawej ramki + pasujące z lewej)'))
right_join = produkty.join(magazyn, how='right')
display(right_join)

display(Markdown('>> ### WSZYSTKIE REKORDY'))
outer_join = produkty.join(magazyn, how="outer")
display(outer_join)

display(Markdown('>> ### WSPÓLNE REKORDY'))
inner_join = produkty.join(magazyn, how="inner")
display(inner_join)

>> ### LEFT JOIN (wszystkie wiersze z lewej ramki + pasujące z prawej)

                 nazwa  cena  kategoria  stan lokalizacja ostatnia_dostawa
produkt_id
101             Laptop  3500         PC  15.0          A1       2024-03-01
102               Mysz   120  Akcesoria   0.0          B3       2024-01-15
103            Monitor   900         PC   8.0          A2       2024-03-10
104         Klawiatura   250  Akcesoria   NaN         NaN              NaN
105          Słuchawki   400      Audio   NaN         NaN              NaN

>> ### RIGHT JOIN (wszystkie wiersze z prawej ramki + pasujące z lewej)

              nazwa    cena  kategoria  stan lokalizacja ostatnia_dostawa
produkt_id
101          Laptop  3500.0         PC    15          A1       2024-03-01
102            Mysz   120.0  Akcesoria     0          B3       2024-01-15
103         Monitor   900.0         PC     8          A2       2024-03-10
106             NaN     NaN        NaN    32          C1       2024-02-20
107             NaN     NaN        NaN     5          B1       2024-03-05

>> ### WSZYSTKIE REKORDY

                 nazwa    cena  kategoria  stan lokalizacja ostatnia_dostawa
produkt_id
101             Laptop  3500.0         PC  15.0          A1       2024-03-01
102               Mysz   120.0  Akcesoria   0.0          B3       2024-01-15
103            Monitor   900.0         PC   8.0          A2       2024-03-10
104         Klawiatura   250.0  Akcesoria   NaN         NaN              NaN
105          Słuchawki   400.0      Audio   NaN         NaN              NaN
106                NaN     NaN        NaN  32.0          C1       2024-02-20
107                NaN     NaN        NaN   5.0          B1       2024-03-05

>> ### WSPÓLNE REKORDY

              nazwa  cena  kategoria  stan lokalizacja ostatnia_dostawa
produkt_id
101          Laptop  3500         PC    15          A1       2024-03-01
102            Mysz   120  Akcesoria     0          B3       2024-01-15
103         Monitor   900         PC     8          A2       2024-03-10

In [29]:
# analizujemy left_join
left_missing = left_join[left_join['stan'].isna()]
display(Markdown('>> ### Rekordy bez wpisu w "magazynie"'))
display(left_missing)

# analizujemy right_join
right_missing = right_join[right_join['cena'].isna()]
display(Markdown('>> ### Rekordy magazynowe bez wpisu w "produktach"'))
display(right_missing)

>> ### Rekordy bez wpisu w "magazynie"

                 nazwa  cena  kategoria  stan lokalizacja ostatnia_dostawa
produkt_id
104         Klawiatura   250  Akcesoria   NaN         NaN              NaN
105          Słuchawki   400      Audio   NaN         NaN              NaN

>> ### Rekordy magazynowe bez wpisu w "produktach"

           nazwa  cena kategoria  stan lokalizacja ostatnia_dostawa
produkt_id
106          NaN   NaN       NaN    32          C1       2024-02-20
107          NaN   NaN       NaN     5          B1       2024-03-05


----
### UWAGA! Eksplozja wierszy

In [30]:
# EKPLOZJA WIERSZY!

import pandas as pd

# Lewa ramka: Promocje w sklepach
df_promocje = pd.DataFrame({
    'sklep_id': [101, 101, 101],
    'promocja': ['Gratis', 'Rabat 20%', 'Darmowa dostawa']
})

# Prawa ramka: Pracownicy w sklepach
df_pracownicy = pd.DataFrame({
    'sklep_id': [101, 101, 101],
    'pracownik': ['Anna', 'Jan', 'Marek']
})

df_pracownicy_unique = pd.DataFrame({
    'sklep_id': [101, 102, 103],
    'pracownik': ['Anna', 'Jan', 'Marek']
})

# Łączenie ramek (wiele do wielu)
wynik = pd.merge(df_promocje, df_pracownicy, on='sklep_id')
display(wynik)

   sklep_id         promocja pracownik
0       101           Gratis      Anna
1       101           Gratis       Jan
2       101           Gratis     Marek
3       101        Rabat 20%      Anna
4       101        Rabat 20%       Jan
5       101        Rabat 20%     Marek
6       101  Darmowa dostawa      Anna
7       101  Darmowa dostawa       Jan
8       101  Darmowa dostawa     Marek

In [40]:
from pandas.errors import MergeError

# Wymuszamy relację many_to_one
try:
    wynik_bezpieczny = pd.merge(
        df_promocje, 
        df_pracownicy, 
        on='sklep_id', 
        validate='many_to_one' # one_to_one | one_to_many | many_to_one | many_to_many
    )
    display(wynik_bezpieczny)
except MergeError as e:
    display(Markdown(f"<font size=5 color='#ff7777'>### Błąd! Wykryto eksplozję danych: {e}</font>"))

<font size=5 color='#ff7777'>### Błąd! Wykryto eksplozję danych: Merge keys are not unique in right dataset; not a many-to-one merge</font>

In [39]:
from pandas.errors import MergeError

# Wymuszamy relację many_to_one
try:
    wynik_bezpieczny = pd.merge(
        df_promocje, 
        df_pracownicy_unique, 
        on='sklep_id',
        how="outer",
        validate='many_to_one' # one_to_one | one_to_many | many_to_one | many_to_many
    )
    display(wynik_bezpieczny)
except MergeError as e:
    display(Markdown(f"<font size=5 color='#ff7777'>### Błąd! Wykryto eksplozję danych: {e}"))

   sklep_id         promocja pracownik
0       101           Gratis      Anna
1       101        Rabat 20%      Anna
2       101  Darmowa dostawa      Anna
3       102              NaN       Jan
4       103              NaN     Marek